// Derived from ECDICT's IELTS/TOEFL-tagged entries (MIT License).
// Keep the compact TSV form so the client bundle does not carry unused dictionary fields.
export const ACADEMIC_WORD_DATA = `
even	甚至；即使；均匀的
mean	意味着；平均的；平均值
system	系统；体系；制度
issue	问题；议题；发布
community	社区；群体；共同体
interest	兴趣；利益；利息
offer	提供；提议；报价
effect	影响；效果；结果
process	过程；流程；处理
team	团队；小组
major	主要的；重大的；主修
action	行动；措施；作用
economic	经济上的；实用的；节省的
figure	数字；人物；图表
role	角色；作用；职责
period	时期；节段；节
term	术语；期限；学期
available	可利用的；可获得的；有效的
condition	条件；状况；限制
project	项目；计划；预测
evidence	根据；证据；迹象
involve	包括；使陷于；潜心于
cause	原因；导致；事业
general	一般的；总体的；普遍的
authority	权力；当权者；当局
rule	规则；统治；控制
site	地点；场所；网站
staff	员工；全体人员；配备人员
section	区段；部分；区域
opportunity	机会；时机
private	私人的；秘密的；私立的
sort	种类；方式；品质
quality	质量；品质；特性
represent	表现；表示；描绘
approach	方法；接近；处理
choice	选择；精选品；选择权
performance	表现；绩效；执行
occur	发生；被想到；存在
claim	主张；声称；权利
current	当前的；流通的；趋势
financial	财政的；金融的
pressure	压力；强制；压强
range	范围；系列；变化区间
image	影像；肖像；想象
standard	标准；规范；通常的
apply	应用；申请；适用
benefit	利益；有益于；受益
various	不同的；各种的；多方面的
firm	公司；坚定的；稳固的
treatment	治疗；待遇；处理
design	设计；图样；方案
media	媒体
analysis	分析
identify	识别；认为等同于；确定
resource	资源；财力；办法
serious	严肃的；认真的；重要的
property	财产；所有权；性质
culture	文化；修养；耕种
campaign	战役；运动；竞选运动
charge	费用；负责；指控
compare	比较；比喻；对照
goal	目标；终点；得分
legal	法律的；法定的；合法的
affect	影响；感动；假装
avoid	避免；防止；撤消
achieve	完成；达到；如愿以偿
check	检查；支票；阻止物
conference	会议
specific	具体的；特定的；明确的
popular	通俗的；流行的；受欢迎的
institution	机构；惯例；制度
committee	委员会
contract	合约；婚约；契约
responsibility	责任；职责；负担
executive	执行的；善于执行的；善于经营的
attempt	尝试；企图
strategy	战略；策略
assume	假定；承担；呈现
customer	消费者
successful	成功的；一帆风顺的；顺利的
administration	行政；管理；政府机关
normal	正常的；正规的；标准的
professional	专业的；职业的；专业人才
original	最初的；原始的；有创意的
edge	边缘；尖锐；刀刃
employee	职员；员工；受雇人员
trial	审讯的；试验性的；审判
majority	多数；大半
notice	注意；布告；通知
version	一种描述；版本；译文
previous	早先的；前面的；过急的
access	通路；入口；接近
budget	预算；编预算；编入预算
union	联盟；联合；结合
application	应用；申请；志愿书
effective	有效的；有力的；实际的
variety	多样；种类；变种
title	头衔；名称；标题
candidate	候选人；投考者
species	种；类；外形
option	选择权；挑选；选项
opinion	意见；评价；主张
eventually	最后；终于
complete	完全的；十足的；完成的
positive	肯定的；积极的；有把握的
survey	纵览；视察；测量
commercial	商业的；商用的；商品化的
procedure	程序；过程；手续
solution	解决；解答；溶液
communication	交流；交通；通讯
facility	设施；设备；便利
reform	改革；改正；改造
congress	国会；会议；讨论会
competition	竞争；竞赛
scale	规模；尺度；等级
release	释放；发泄；豁免
status	状态；情形；地位
appropriate	适当的
target	目标；指标；针对
credit	学分；信用；认可
track	跟踪；轨迹；途径
direct	直接的；坦白的；指示
strike	罢工；打击；殴打
context	上下文；背景；来龙去脉
extend	扩充；延伸；伸展
equipment	装备；设备；才能
strength	力量；实力；强度
consumer	消费者
presence	出席；面前；存在
challenge	挑战；盘问；向挑战
prime	主要的；首要的；全盛期
distance	距离；远方；遥远
review	检讨；复习；回顾
audience	听众；观众；读者
conflict	战斗；冲突；矛盾
address	处理；演说；地址
associate	联系；交往；同事
investigation	调查；审查
observe	觉察到；遵守；注意到
profit	利润；赢利；利益
exchange	交换；交换局；交换机
association	协会
advice	忠告；劝告；意见
focus	重点；聚焦；焦点
vehicle	交通工具；车辆；传播媒介
additional	附加的；另外的；额外的
comment	注解；批评；评论
regular	规则的；常例的；有秩序的
sample	样本；范例；抽样
deny	否认；拒绝
contact	联系；接触；联系人
primary	主要的；首要的；初级的
circumstance	环境；状况；事件
potential	有潜力的；可能的；潜在的
critical	批评的；决定性的；危险的
extent	范围；程度；区域
promote	促进；晋升；创办
recall	回忆；召回；撤消
industrial	工业的；供工业用的；工业高度发展的
commit	委托；犯罪；指派作战
adopt	采用；正式通过；收养
appeal	恳求；诉请；上诉
assessment	评估；估定；评定的款额
construction	建筑；构造；建筑物
obvious	明显的；明白的；显然的
category	种类；类项
sector	扇形；部门；部分
injury	伤害；侮辱
score	得分；抓痕；二十个
file	文件；档案；提交
promise	允诺；约定；预示
sight	景观；视力；眼界
domestic	家庭的；国内的；驯养的
complex	复杂的；综合体；情结
requirement	需求；必要条件；要求
commitment	委托；交押；承担义务
session	期间；开庭期；会议
propose	计划；打算；建议
confirm	证实；确定；批准
content	内容；满足的；含量
package	包裹；套装软件；包
combine	联合；结合；联合收割机
faith	信心；信任；忠实
regulation	规则；管理；调整
estate	不动产；阶段；阶层
essential	必要的；本质的；要素
payment	付款；支付的款项；偿还
traffic	交通；通行；运输
location	位置；场所；特定区域
internal	内在的；国内的
instruction	指令；教导；命令
remind	提醒；使想起
loan	贷款；借出；借
launch	下水；汽艇；发射
desire	欲望；要求；想要
sheet	床单；张；纸张
debt	债务；罪过
religion	宗教；信仰
relief	减轻；解除；救济
mental	心智的；精神病的；心理的
confidence	信心
contrast	差别；对比；对照物
weather	天气；气象；处境
temperature	温度；发烧；热度
camp	露营；帐篷；扎营
declare	宣布；声明；申报
volume	册；卷；体积
commission	委任状；任官令；所委职责
capacity	容量；能力；才能
instrument	工具；手段；仪器
circle	圆周；社交圈；循环
occasion	场合；时机；机会
theme	主题；话题；题目
equal	相等的；平等的；胜任的
sale	出售；卖；拍卖
legislation	立法；法律
component	组成的；构成的；元件
provision	钱和设备；准备；供应品
academic	学院的；学术的；不切实际的
generate	产生；发生；导致
engage	答应；从事；交战
representative	描写的；表现的；代理的
revenue	收入；岁入；税收
technical	技术上的；专门的；工业的
panel	嵌板；仪表板；专题讨论小组
initial	开始的；最初的；字首的
acquire	获得；学到
silence	沉默；无声；静寂
explore	探险；探测；探究
democracy	民主政治；民主主义
negative	否定的；消极的；负的
overall	全部的；全体的；从头至尾的
investigate	调查；审查
global	通用的；全球的；球形的
plastic	塑料的；塑造的；有可塑性的
rural	乡下的；田园的；乡村风味的
assess	估定；对征税；评定
suit	套装；诉讼；请求
practical	实际的；现实的；实用性的
afford	买得起；足以；给予
motion	移动；手势；动作
rely	信赖；依赖；信任
asset	资产；有益的东西
scheme	方案；计划；组合
slip	滑；滑行；事故
employer	雇主；老板
arise	站立；出现；起来
estimate	估计；判断；评价
selection	选择；选文；精选品
trend	趋势；倾向；走向
consist	组成；存在于；一致
notion	概念；观念；想法
typical	典型的；象征性的
formal	正式的；形式的；礼仪的
mission	任务；代表团；使命
rare	稀罕的；罕有的；珍奇的
outcome	结果；出口
entry	登录；条目；进入
appreciate	赏识；鉴别；为而感激
discipline	训练；纪律；惩罚
objective	客观的；如实的；无偏见的
liberal	慷慨的；不拘泥的；宽大的
minority	少数；未成年；少数民族
novel	小说；长篇故事；新奇的
tear	泪滴；眼泪；撕
curriculum	课程
fashion	流行；风尚；时样
display	显示；陈列；炫耀
unique	独一无二的；独特的；稀罕的
welfare	福利；安宁；幸福
stress	压力；紧迫；强调
alternative	两者择一的；供选择的；两者择一
distribution	分配
blame	过失；责备；归咎于
priority	优先权；优先
characteristic	特性的；特有的；有特色的
stretch	伸展；张开；连绵
mass	块；大多数；质量
impose	征；把强加于；以欺骗
pilot	飞行员；领航员；航船者
intelligence	智力；情报；信息
somewhat	某物；几分；多少
vary	改变；使多样化；变化
abuse	滥用；虐待；恶习
exhibition	表现；展览会；展览品
transfer	迁移；移动；传递
topic	主题；论题；话题
accuse	指责；控告；归咎于
phase	时期；局面；方面
chest	胸；胸部；衣柜
recover	重新获得；恢复；复原
request	请求；需要；申请书
observation	观察；注意；观测
height	高度；海拔；高地
achievement	完成；成就；功业
shift	变化；移动；轮班
contemporary	同时代的；属于同一时期的；同时代的人
flat	平坦的；单调的；无力的
illustrate	举例说明；作图解；阐明
resolution	解析；决心；坚定
massive	大而重的；宽大的；宏伟的
regime	政权；当权期间；政体
prospect	景色；展望；勘探
enterprise	企业；事业心；进取心
cabinet	橱柜；内阁；内阁的
virtually	事实上
sharp	半升音调；利刃；骗子
grand	庄重的；壮观的；显赫的
landscape	风景；山水；风景画
diet	日常饮食；议会；照规定饮食
solve	解决；付给；溶解
enormous	巨大的；庞大的
publication	出版物；出版；公布
permit	许可证；许可；执照
channel	海峡；航道；频道
supreme	至高；霸权；至高的
attach	附上；使依附；使附属
retain	保持；保有；留住
territory	领土；领地；版图
medium	媒体；方法；媒介
variable	可变的；不定的；易变的
severe	严格的；尖锐的；严肃的
grab	抓握；掠夺；强占
suspect	被怀疑者；嫌疑犯；令人怀疑的
whereas	然而；鉴于
bond	捆绑物；结合；债券
participate	参加；分享；参与
tension	紧张；不安；拉紧
shock	震动；冲突；震惊
assumption	假定；自负；担任
constant	不变的；一定的；时常的
proportion	比例；比率；均衡
complaint	诉苦；抱怨；控诉
finance	财政；财务；供给经费
unlikely	不太可能的
intervention	插入；介入；调停
accompany	陪伴；伴随；补充
catholic	天主教的；普遍的；广泛的
dominate	支配；占优势
fundamental	基本的；重要的；原音的
dramatic	戏剧性的；生动的
capture	抓取；战利品；捕获之物
rarely	很少地；罕有地
deputy	副手；代理人
percentage	百分比；比率；部分
personality	个性；人格；特有特性
crucial	决定性的；重要的；严厉的
perception	知觉；感觉；领悟力
layer	层；产卵鸡；放置者
resolve	决定；分解；决心
convention	大会；协定；惯例
implement	工具；器具；手段
witness	证人；目击者；证据
origin	起源；起因；出身
exception	例外；除外；异议
permanent	永久的；不变的；固定的
preserve	保护；保持；保存
oppose	反对；以对抗；抗争
resistance	抵抗力；反抗；耐力
tower	塔；高楼；堡垒
mechanism	机械；机构；结构
square	正方形；街区；广场
chip	屑片；薄片；碎片
switch	开关；电闸；转换
emotion	情绪；激动；强烈的情感
appointment	约会；委任的职位；委派
expose	使暴露；使曝光；揭穿
symptom	症状；征候；征兆
surgery	外科；手术；手术室
bend	变弯曲；屈服；使弯曲
reputation	名誉；名声；声望
visual	视觉的
mood	心情；气氛；生气
sufficient	充分的；足够的
silver	银；银币；银器
variation	变更；变化；变种
incorporate	合并的；组成公司的；一体化的
champion	冠军；拥护者；战士
occupy	占领；占；住进
jury	陪审团；评判委员会；应急的
journalist	新闻记者；从事新闻杂志业的人
withdraw	撤回；取回；撤消
protein	蛋白质；蛋白质的
vital	生命的；重要的；充满活力的
ideal	理想的；完美的；空想的
external	外部的；客观的；表面的
restore	回复；恢复；归还
dispute	争论
approval	赞成；批准
monitor	监督器；级长；监听员
distinction	区别
proceed	继续进行；进行；开始
disaster	灾祸；不幸；彻底失败
opposite	相对的；相反的；对面的
pure	纯的；纯净的；纯洁的
boundary	边界；分界线
sequence	序列；续发事件；顺序
acid	酸；酸类物质；尖刻
string	线；细绳；一串
opponent	敌对的；反对的；对面的
schedule	时间表；一览表；计划表
deserve	该得到；值得；应得报答
phenomenon	现象；迹象；表现
numerous	很多的；数目众多的；多数的
retirement	退休；隐居；撤退
sensitive	敏感的；易感的；灵敏的
slide	滑；滑道；山崩
dismiss	解散；开除；解职
cite	引用；引证；表彰
fault	过错；故障；毛病
swing	摇摆；振幅；音律
drama	戏剧；戏剧艺术
perceive	感觉；认知；理解
eliminate	除去；排除；剔除
violent	暴力的；猛烈的；激烈的
pose	姿势；姿态；装模作样
ethnic	人种的；种族的
recommendation	推荐；介绍；推荐信
penalty	处罚；刑罚；罚款
pace	速度；步调；步法
poverty	贫穷；贫困；缺乏
enhance	提高；加强；增加
routine	常规；日常工作；惯例
alter	改变
mode	模态；调式；样式
nervous	神经紧张的；不安的；神经的
extensive	广的；广泛的；多方面的
cable	电缆；海底电报；缆
chamber	室；房间；枪膛
rough	粗糙的东西；毛坯；未加工品
pollution	污染；玷污
protest	抗议；反对；抗议书
gallery	走廊；最高楼座；画廊
anxiety	焦虑；忧虑；令人焦虑的事
consultant	顾问；征询意见者
expansion	扩充；开展；膨胀
furniture	家具；帆具
profession	职业；表白；声明
smooth	平滑的；平稳的；流畅的
install	安装；安置；使就职
adjust	调整；使适应于；校准
rank	等级；排；横列
dimension	尺寸；次元；面积
transition	转变；转换；变迁
remarkable	不平常的；值得注意的；显著的
convert	皈依者；改变宗教信仰者；使改变信仰
framework	结构；骨架；参照标准
agenda	议程；日常工作事项
constitute	构成；组成；任命
stomach	胃；食欲；欲望
barely	几乎不
obligation	义务；责任；约束
fiber	纤维；构造；纤维制品
infection	传染；影响；传染病
tube	管；软管；隧道
wrap	外套；围巾；包裹物
depression	不景气；消沉；沮丧
assure	保证；使确信；弄清楚
slight	轻蔑；怠慢；轻微的
inflation	胀大；夸张；通货膨胀
coalition	结合体；结合；联合
barrier	障碍；栅栏
passion	激情；酷爱；热爱
survival	赖以生存的；生存；残存
convince	说服；使相信
shell	贝壳；壳；外形
detect	发现；察觉；探测
maintenance	维护；保持；维修
sweep	扫除；打扫；肃清
journal	日记；杂志；日报
radical	激进的；根本的；基本的
charity	慈悲；博爱；慈善团体
volunteer	志愿者；志愿的；自愿
platform	站台；月台；讲台
guarantee	担保；抵押品；保证书
statistics	统计学；统计资料
extension	延长；扩充；范围
deficit	赤字；不足额
spiritual	精神上的；神圣的；崇高的
rail	横杆；围栏；栏杆
custom	习惯；风俗；海关
entrance	入口；进入点；入场
principal	主要的；最重要的；首要的
stake	桩；炮烙刑；木柱
exposure	暴露；揭发；揭露
distant	远的；疏远的
subsequent	后来的；接下去的
sink	藏垢的场所；沟渠；污水槽
exclude	除外；排除；排斥
tendency	趋向；倾向
submit	使服从；使受到；委托
confident	有信心的；有把握的
laboratory	实验室；研究室；化工厂
temporary	暂时的；临时的；临时工
ratio	比；比率
concert	音乐会；和声；一致
draft	气流；草稿；汇票
satisfaction	满足；满意；快事
accurate	正确的；精确的
tissue	薄的织物；薄纱；棉纸
profile	侧面；轮廓；传略
intense	非常的；强烈的；紧张的
inspire	使感动；激发；启示
evaluate	评估；评价；赋值
distinguish	区别；辨别
confront	使面对；对抗；遭遇
ally	同盟者；同盟国；助手
entertainment	娱乐；款待；娱乐表演
hence	因此；从此
secondary	中级的；中等的；次要的
dependent	依赖的；从属的；依赖他人者
emphasize	强调；加强语气；着重
assistant	有帮助的；辅助的；助理的
therapy	治疗
register	寄存器；记录；登记簿
encounter	相会；相遇；遭遇
distribute	分配；散布；分发
universal	全世界的；普遍的；宇宙的
desert	沙漠；应得的赏罚；功劳
delay	耽搁；迟滞；延迟
undertake	试图；从事；保证
storage	存储器；储藏；保管
preference	偏爱；优先；喜爱物
clinic	诊所；临床教学
adequate	适当的；足够的
tongue	舌；语言能力；讲话方式
chart	图表；海图；制成图表
consumption	消费；消费量；痨病
vessel	船；容器；脉管
alliance	联盟；联合
qualify	取得资格；有资格；使有资格
sustain	承受；支持；供养
strengthen	加强；变坚固；变强
admission	准许进入；入场费；录用
pitch	程度；坡度；顶点
assault	攻击；袭击；发动攻击
fabric	织物；布；结构
steady	稳定的；不动摇的；沉着的
strip	长条；条状；带
recession	后退；凹处；衰退
currency	货币；通货；流通
sake	目的；缘故；理由
craft	技艺；手艺；诡计
distinct	清楚的；显著的；不同的
shelf	架子；搁板
transaction	交易；办理；学报
resort	度假胜地；手段；凭借
defeat	败北；失败；击败
trace	痕迹；踪迹；微量
dominant	占优势的；支配的
conservation	保护；保存
intellectual	智力的；用脑力的；聪明的
pregnant	怀孕的；充满的；思想丰富的
conviction	定罪；信服；坚信
composition	作文；创作；组成
occupation	职业；占有；占有期
possession	拥有；占有；所有
impressive	给人深刻印象的；威严的
formula	客套语；公式；准则
flag	标志；旗标；旗子
psychology	心理学；心理状态
vulnerable	易受伤害的；有弱点的；易受影响的
smart	聪明的；漂亮的；刺痛的
satellite	人造卫星
curve	曲线；弯曲；曲线球
remark	评论；注意；谈论
economics	经济学
trail	踪迹；痕迹；一串
incentive	激励的；动机
literally	逐字地；按照字面上地；不夸张地
ceremony	典礼；仪式；礼节
infant	婴儿的；幼稚的；婴儿
yield	生产量；投资收益；出产
absorb	吸收；使全神贯注；同化
exceed	超过；超越；胜过
gear	齿轮；工具；以齿轮连起
evolution	进化；发展；进展
faculty	才能；能力；全体教员
desperate	不顾一切的；危急的；令人绝望的
confusion	混乱；混淆；无秩序
maximum	极点；最大量；极大
crash	哗啦声；猛撞；崩溃
plot	小块土地；地区图；图
constitution	构成；宪法；体格
carbon	碳；副本；复写纸
festival	节日的；喜庆的；快乐的
mutual	相互的；共有的
prominent	卓越的；显著的；突出的
behave	举止端正；行为规矩；检点行为
tunnel	隧道；地下道；挖隧道
insight	察看；洞察力；见识
summit	顶点；最高阶层；最高级会议
aggressive	侵略的；挑畔的；进取的
reinforce	加强；增援；补充
recipe	食谱；处方；秘诀
gentle	温和的；文雅的
venture	冒险；风险；敢于
innocent	无罪的；不懂事的；无知的
undergo	遭受；经历；忍受
wander	游荡；漫步；徘徊
reward	报酬；酬谢；赏金
reserve	储备品；贮量；后备军
architecture	建筑学；建筑式样
highlight	加亮区；精彩场面；加亮
episode	插曲；插话；有趣的事件
tournament	比赛；竞赛；锦标赛
trick	诡计；欺诈；谋略
architect	建筑师；设计者；缔造者
tremendous	巨大的；非常的；可怕的
margin	页边的空白；边缘；界限
genuine	真正的；真实的；诚恳的
modest	谦逊的；羞怯的；端庄的
squeeze	紧握；挤；榨
virus	病毒；滤过性病毒；毒害
anticipate	预期；占先；加速
suitable	适当的；相配的
stability	安定；稳定性；坚实
collapse	崩溃；倒塌；虚脱
peer	同等的人；匹敌；贵族
prompt	激励；提示；提醒物
controversy	论争；辩论；论战
minimum	最小的；最低的；最小值
entitle	给权利；取名为；给予名称
flee	逃避；逃跑；逃走
patch	片；补缀；碎片
frequent	时常发生的；频繁的；快速的
fade	褪色；消失；凋谢
tragedy	悲剧；惨案；悲剧作品
enthusiasm	巨大的热情；热心
flame	火焰；火舌；热情
compensation	补偿；赔偿金；工资
strain	紧张；拉紧；张力
consult	商讨；商量；协商
acquisition	获得；获得物
ingredient	成分；因素
sigh	叹息；渴望；叹息着说
agriculture	农业
equation	相等；等式；平衡
embrace	拥抱；互相拥抱；包含
grain	谷粒；颗粒；谷类
portion	部分；一份；命运
conscious	有意识的；知觉的；觉察的
spin	旋转；自旋；疾驰
assign	分配；指派；赋值
myth	神话；虚构的事；虚构的人
compose	组成；写作；作曲
theoretical	理论的；理论上的；假设的
identification	识别；身份证明；认同
organic	器官的；有机的；组织的
overlook	俯瞰；远眺；没注意到
controversial	争论的；论争的；被议论的
uniform	制服；统一的；一律的
slope	倾斜；斜坡；斜率
circuit	电路；环道；巡回
companion	朋友；陪伴；指南
precise	精确的；严谨的；明确的
attribute	属性；标志；定语
battery	电池；殴打
fantasy	幻想；想象的产物
genetic	创始的；遗传的；起源的
bare	赤裸的；缺少的；无遮蔽的
privilege	特权；特别恩典；基本权利
devote	投入于；献身
determination	决心；果断
float	漂流物；浮舟；漂浮
hypothesis	假设
logic	逻辑；逻辑学；推理的方法
reverse	相反；背面；倒退
naked	裸体的；无装饰的；无保护的
crack	裂缝；爆裂声；爆裂
detective	侦探的；侦探
rhythm	旋律；节奏；韵律
deck	甲板；行李仓；装饰
ideology	思想体系；意识形态；观念学
stroke	笔划；打；中风
tackle	工具；复滑车；滑车
structural	结构的；建筑的
heritage	遗产；祖先遗留物；继承物
reliable	可靠的；可信赖的
integrate	综合；使完整；使成整体
inspection	检验；检查；视察
interior	内部；内政；内部的
utility	功用；有用之物；实用
thereby	因此
innovation	改革；创新
presumably	推测上；大概
recruit	新兵；新手；新会员
repair	修理；补救；修复
clue	线索；暗示；提供线索
swallow	燕子；吞咽；喉
expenditure	开支；费用；用光
divorce	离婚；与离婚
particle	颗粒；粒子；质点
render	回报；给于；付给
terror	恐怖；可怕的人
readily	迅速地；轻易地；乐意地
scandal	丑闻；中伤；耻辱
reception	接待；接受；招待会
expertise	专家意见；专门技术
resemble	相似；类似
suspend	悬；吊；使悬浮
steam	蒸汽；精力；蒸汽的
comprise	包含；构成
trap	圈套；陷阱；诡计
shower	阵雨；淋浴；一阵
superior	长者；占优势的人；上级
practitioner	从业者；开业者
echo	回声；回音；回波
horizon	地平线；眼界；视地平
assignment	分配；功课；任务
initiate	入会；开始；新加入的
elite	精华；精锐；中坚分子
shelter	庇护所；避难所；庇护
voluntary	自动的；自愿的；故意的
domain	领域；领土；产业
crystal	水晶的；水晶一样的；透明的
essence	实质；本质；香精
compound	混合物；复合词；化合物
explode	爆炸；爆发；激增
leap	跳跃；剧增；急变
generous	慷慨的；有雅量的；大量的
temple	圣堂；庙宇；教堂
grip	紧握；柄；握力
deposit	存款；定金；堆积物
retail	零售；零售的；详述
boom	繁荣；隆隆声；急速发展
identical	同一的；恒等的；完全相同的
cancel	取消；撤消；盖销
norm	基准；模范；标准
undermine	在下面挖；渐渐破坏；暗地里破坏
colony	殖民地；移民队
accommodate	使适应；调和；通融
drift	漂流物；漂流；动向
exclusive	排外的；独占的；唯一的
cease	停止；终了
concrete	凝结物；混凝土；具体的
bunch	串；束
sculpture	雕刻；雕塑；当雕刻师
regardless	不管；不注意；不顾
mask	面具；假面具；掩饰
fraud	欺骗；欺诈；诡计
consensus	合意；一致；同感
subtle	敏锐的；精细的；狡猾的
automatic	自动的；机械的；必然的
outline	大纲；轮廓；概要
regulate	管理；控制；调节
lamp	灯；照亮
tide	潮；潮汐；趋势
plead	辩护；恳求；为辩护
segment	片段；部分；分节
intelligent	聪明的；智能的；了解的
interval	间隔；距离；间歇
coin	硬币；金钱；货币
oral	口头的；口述的；口部的
execute	执行；实行；完成
doctrine	教条；学说
surgeon	外科医生；军医；船医
flexible	易曲的；灵活的；柔顺的
magic	魔术的；有魔力的；不可思议的
condemn	判刑；责备；谴责
equivalent	相等的；相当的；同意义的
comedy	喜剧；有趣的事情
miracle	奇迹；奇事
hint	暗示；提示；示意
harsh	粗糙的；刺耳的；严厉的
legend	传说；传奇文学；图例
rival	竞争的；对手；竞争者
exploit	功绩；勋绩；开发
reluctant	不情愿的；勉强的
tune	歌曲；主旋律；心情
residence	住宅；居留；驻扎
random	随意；随机；任意的
shortage	不足；缺乏
twist	一扭；扭曲；曲折
compromise	妥协处理；妥协；折中
convey	传达；运输；转让
sanction	核准；制裁；处罚
charter	特许状；执照；宪章
hardware	硬件；五金器具；零件
fluid	液体；分泌液；流体
ambition	野心；志向
spectrum	光谱；范围；系列
assemble	集合；收集；装配
container	容器；集装箱
flash	闪光；闪现；一瞬间
artificial	人造的；假的；非原地产的
diplomatic	外交的；老练的
solar	太阳的；日光的；源自太阳的
drain	排水沟；消耗；排水
lawn	草地；草坪；上等细麻布
publicity	名声；宣传；公开场合
monster	怪物；恶人；巨物
tribe	宗族；部落；一群人
barrel	桶；装入桶内
decent	有分寸的；得体的；大方的
delicate	细致优雅的；微妙的；美味的
fitness	适合；合宜；合理
sheer	绝对的；全然的；纯粹的
cluster	串；丛；群
depict	描述；描写
sponsor	保证人；赞助者；发起者
decrease	减少；减少量
resume	重新开始；取回；恢复
limb	四肢；枝干；翼
diverse	不同的；变化多的
discount	折扣；贴现率；打折扣
questionnaire	调查表；问卷
elbow	手肘；弯头；扶手
objection	异议；反对；不喜欢
chronic	慢性的；习惯性的；慢性病患者
ridiculous	荒谬的；可笑的
slice	薄的切片；一部分；菜刀
beam	横梁；杆；光线
boost	推进；吹捧；提高
rational	理性的；合理的；有理数
rescue	援救；解救；营救
abstract	抽象的；深奥的；摘要
casual	偶然的；不经意的；便装的
colonial	殖民的；殖民地的
characterize	描绘的特性；刻划的性格
pump	抽水机；打气筒；泵
poster	海报；招贴；驿马
steep	浸渍；悬崖；险峻的
elegant	优雅的；端庄的；高雅的
dump	垃圾场；倾倒；倾销
stimulus	刺激；激励；刺激品
conversion	转变；转换；改变宗教信仰
isolate	使隔离；使孤立；使绝缘
entity	实体；实存物；存在
sole	脚掌；鞋底；底部
faint	昏厥；昏倒；模糊的
chaos	大混乱；混沌
integrity	正直；廉正；完整
moderate	适度的；稳健的；中等的
disturb	扰乱；妨碍；使不安
spectacular	公开展示的；惊人的；壮观的
counterpart	副本；复本；配对物
mathematics	数学
cliff	悬崖；绝壁
transmission	传输；传送；变速器
timber	木材；木料；用木材建造
scatter	消散；分散；散播
conception	观念；概念
accomplish	完成；达到；实现
prior	更重要的；较早的；在先的
ritual	仪式的；依仪式进行的；仪式
flavour	味；调味香料；滋味
attendance	出席；出席的人数；照料
monetary	货币的；金钱的
stem	茎；干；柄
filter	滤波器；过滤器；滤光器
bonus	奖金；红利
incredible	难以置信的
conceive	构思；认为；怀孕
descend	下降；世代相传；屈尊
cabin	小屋；客舱；关在小屋
enroll	登记；使加入；参军
stimulate	刺激；激励；鼓舞
ward	病房；守卫；保卫
bulk	大小；体积；大块
sacred	神圣的；献给上帝的；庄严的
accuracy	精确；正确
youngster	小孩；年轻人；少年
signature	签字；识别标志；调号
molecule	分子；些微
confess	承认；坦白；忏悔
concede	承认；退让；让步
fist	拳头；手；拳打
comply	顺从；依从
vanish	消失；不见；成为零
instinct	本能；直觉；充满着的
endorse	支持；赞同；背书于
panic	惊慌的；没有理由的；恐慌的
obstacle	障碍；妨害物；阻碍
fragment	碎片；破片；片段
insert	插入物；插入；把射入
precious	宝贵的；珍贵的；过于精致的
profound	极深的；深厚的；深刻的
medieval	中古的；中世纪的
unfair	不公平的；不正直的；不正当的
persist	坚持；固执；持续
merit	优点；功绩；价值
spill	溢出；溅出；摔下
subsidy	补助金；津贴
immigrant	移入的；移民的；移民
casualty	意外事故；伤亡；受害者
devise	设计；发明；图谋
physician	医师；内科医师；解除痛苦者
athlete	运动员；运动选手
confuse	使混乱；使狼狈；使困惑
triumph	凯旋；胜利；欢欣
destination	目的地；目标；目的
dynamic	动态的；有活力的；有力的
stiff	坚硬的；严厉的；呆板的
execution	实行；完成；执行
inadequate	不充分的；不适当的
fraction	小部分；破片；分数
confine	限制；使不外出；禁闭
pine	松树；松木；消瘦
thumb	拇指；以拇指拨弄；笨拙地摆弄
metropolitan	大都市居民；都主教；宗主国的公民
preliminary	初步的；开始的；预备的
inherit	继承；遗传；接受遗产
remedy	药物；治疗法；治疗
canvas	帆布；画布；油画
civilian	平民；民法专家；平民的
seal	印章；封条；海豹
decorate	装饰
clause	子句；条款
organism	生物；有机体；社会组织
vertical	垂直的；直立的
attorney	代理人；律师
barn	谷仓
hostile	敌人的；怀敌意的；敌对的
array	排列；衣服；大批
verbal	用言辞的；言语的；口头的
partial	部分的；偏袒的；偏爱的
canal	运河；水道；管
practically	几乎；差不多；事实上
bold	大胆的；粗体
orientation	定方位；适应；向东方
dawn	破晓；黎明
provoke	激怒；惹起；诱导
comparable	可比较的；比得上的
drawer	抽屉；开票人
statue	以雕像装饰；雕像
shallow	水浅的地方；浅滩；浅的
sphere	球；球面；球体
dissolve	溶解；解散
verdict	裁决；判决；判断性意见
scholarship	学问；学术成就；奖学金
fierce	凶猛的；猛烈的；热烈的
dedicate	献出；贡献
exclusively	排他地；仅仅；专门
diminish	减少；变小
marine	舰队；水兵；海景画
towel	手巾；毛巾；擦干身子
humanity	人性；人类；博爱
acute	尖锐的；敏锐的；激烈的
neat	整洁的；巧妙的；匀称的
convict	囚犯；罪犯；宣告有罪
productive	能生产的；有生产价值的；多产的
raid	袭击；突袭；搜捕
seemingly	看来似乎；表面上看来
trunk	树干；干线；躯干
bias	偏见；斜纹；偏斜的
accessible	易接近的；可进入的；可使用的
frown	皱眉；皱眉头；皱眉表示
rear	后面；背后；后方
premium	额外补贴；奖金；奖赏
explicit	详述的；清楚的；直言的
inspiration	灵感；鼓舞人心的人或物；妙计
cognitive	认知的；认识的
bounce	跳；跳跃；弹力
induce	引诱；招致；归纳出
ambitious	有野心的；抱负不凡的；雄心勃勃的
cling	粘紧；附着；紧贴
motivate	给与动机；刺激；提高的学习欲望
autonomy	自治；自治权
riot	暴动；喧闹；放纵
thigh	大腿；股
correspond	符合；通信；相当
undoubtedly	无疑；必定；确实地
intent	专心的；决心的；热心的
dilemma	困境；窘境
applicant	申请者
audit	审计；查帐；查
classify	分类；归类；分等
herb	药草；香草
breeze	微风；煤屑；轻而易举的事
sunlight	日光
realm	王国；领土；领域
deem	认为；相信
desirable	令人想望的；可取的
revelation	揭露；泄露；发觉
carve	雕刻；切开
laser	激光
contemplate	注视；沉思；盘算
extract	榨出物；精汁；摘录
veteran	老手；退伍军人；老兵
flour	面粉；粉沫；碎粉
disposal	丢掉；处理；排列
keen	锋利的；敏锐的；强烈的
collaboration	合作；勾结
hierarchy	等级制度；僧侣统治；等级体系
intensive	加强的；内涵的；集中的
rage	愤怒；情绪激动；狂暴
declaration	宣告；说明；宣布
concession	特许；让步；认可
suburb	市郊住宅区；郊区；边缘
crawl	爬行；匍匐而行；养鱼池
dignity	尊严；高贵
rally	重振旗鼓；集合；群众集会
ridge	脊；山脊；山脉
minimal	最小的；极微的；最小限度的
convenient	方便的；合宜的
parade	游行；炫耀；阅兵
galaxy	银河；星系；一群
dull	钝的；无趣的；呆滞的
tender	嫩的；柔软的；脆弱的
`.trim();
